name: new-workflow
on: push
jobs: 
    tests:
        runs-on: ubuntu-lastest
        steps:
            - name: GetCode
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install dependencies
              run: npm CI
            - name: Run Tests
              run: npm test